name: demo_app
description: A new Flutter project.

# SDK constraint
environment:
  sdk: '>=3.9.0 <4.0.0'

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/logo.png
    - assets/background logo.png
    - assets/homepage post.png

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.0.16
  image_picker: ^0.8.4+11
  shared_preferences: ^2.5.3
  path_provider: ^2.1.0

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
