name: demo_app
description: A new Flutter project.

# SDK constraint
environment:
  sdk: '>=3.9.0 <4.0.0'

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/logo.png
    - assets/background logo.png
    - assets/homepage post.png

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
